/**
 * Content Model Simulator — WordPress WXR (eXtended RSS) Reader
 *
 * Zero-dependency parser for WordPress export XML files (WXR 1.2).
 * Extracts posts, pages, authors, categories, tags, and attachments
 * as simulator Document objects.
 *
 * WordPress exports use the WXR format, an XML-based RSS extension
 * with custom wp: namespaced elements. This parser uses targeted
 * string matching (CDATA-aware) instead of a full XML parser to
 * maintain the zero-dependency constraint.
 *
 * Limitation: regex-based extraction assumes well-formed XML
 * generated by WordPress. Hand-edited or malformed WXR files may
 * not parse correctly.
 */

import fs from 'fs';
import path from 'path';
import type { Document } from '../types.js';

// ── Types ────────────────────────────────────────────────────────

export interface WXRReadOptions {
  /** Override the auto-detected locale (from XML &lt;language&gt; tag). */
  locale?: string;
}

export interface WXRSite {
  title: string;
  url: string;
  language: string;
  description: string;
}

export interface WXRResult {
  site: WXRSite;
  documents: Document[];
}

// ── Public API ───────────────────────────────────────────────────

/**
 * Parse a WordPress WXR export file into simulator Documents.
 *
 * Produces documents with the following `contentType` values:
 * - `post`       — Blog posts (body is clean HTML with Gutenberg comments stripped)
 * - `page`       — Static pages
 * - `attachment`  — Media files (images, PDFs, audio, etc.)
 * - `author`     — Site authors
 * - `category`   — Post categories
 * - `tag`        — Post tags
 *
 * Use a custom transformer (`TransformerRegistry`) to map these
 * to your Contentful content types.
 *
 * @example
 * ```ts
 * import { readWXR } from 'content-model-simulator';
 *
 * const documents = readWXR('wordpress-export.xml');
 * // → [{ contentType: 'post', data: { title, slug, body, ... } }, ...]
 * ```
 */
export function readWXR(filePath: string, options: WXRReadOptions = {}): Document[] {
  return parseWXR(filePath, options).documents;
}

/**
 * Parse WXR file and return both site metadata and documents.
 */
export function parseWXR(filePath: string, options: WXRReadOptions = {}): WXRResult {
  const resolved = path.resolve(filePath);
  if (!fs.existsSync(resolved)) {
    throw new Error(`WXR file not found: ${resolved}`);
  }
  const xml = fs.readFileSync(resolved, 'utf-8');
  return parseWXRString(xml, options);
}

/**
 * Parse a WXR XML string directly (useful for testing without file I/O).
 */
export function parseWXRString(xml: string, options: WXRReadOptions = {}): WXRResult {
  const channel = extractFirstBlock(xml, 'channel') || xml;

  const site: WXRSite = {
    title: extractTag(channel, 'title'),
    url: extractSimpleTag(channel, 'link'),
    language: extractTag(channel, 'language') || 'en',
    description: extractTag(channel, 'description'),
  };

  const locale = options.locale || site.language.split('-')[0] || 'en';
  const documents: Document[] = [];

  // Authors (from top-level <wp:author> blocks)
  for (const block of extractBlocks(channel, 'wp:author')) {
    documents.push(parseAuthor(block, locale));
  }

  // Categories (from top-level <wp:category> blocks)
  for (const block of extractBlocks(channel, 'wp:category')) {
    documents.push(parseCategory(block, locale));
  }

  // Tags (from <wp:term> blocks with taxonomy=post_tag)
  for (const block of extractBlocks(channel, 'wp:term')) {
    const taxonomy = extractTag(block, 'wp:term_taxonomy');
    if (taxonomy === 'post_tag') {
      documents.push(parseTagDoc(block, locale));
    }
  }

  // Items — posts, pages, attachments (CDATA-aware extraction)
  for (const block of extractBlocksSafe(xml, 'item')) {
    documents.push(parseItem(block, locale));
  }

  return { site, documents };
}

// ── Item Parser ──────────────────────────────────────────────────

function parseItem(xml: string, locale: string): Document {
  const postType = extractTag(xml, 'wp:post_type') || 'post';
  const title = extractTag(xml, 'title');
  const slug = extractTag(xml, 'wp:post_name');
  const rawContent = extractTag(xml, 'content:encoded');
  const rawExcerpt = extractTag(xml, 'excerpt:encoded');
  const dateGmt = extractTag(xml, 'wp:post_date_gmt');
  const status = extractTag(xml, 'wp:status');
  const creator = extractTag(xml, 'dc:creator');
  const postId = extractTag(xml, 'wp:post_id');
  const attachmentUrl = extractTag(xml, 'wp:attachment_url');

  const { categories, tags } = extractInlineTerms(xml);
  const meta = extractPostMeta(xml);

  // Strip Gutenberg block comments from content
  const body = stripGutenbergComments(rawContent);
  const excerpt = stripGutenbergComments(rawExcerpt);

  const data: Record<string, unknown> = {
    title,
    slug,
    body,
    excerpt,
    publishDate: dateGmt ? toISO(dateGmt) : null,
    status,
    author: creator,
  };

  if (postType === 'attachment') {
    data.url = attachmentUrl;
    data.mimeType = guessMimeType(attachmentUrl || '');
  } else {
    if (categories.length) data.categories = categories;
    if (tags.length) data.tags = tags;
  }

  if (Object.keys(meta).length) data.meta = meta;

  return {
    id: postId || undefined,
    contentType: postType,
    locale,
    path: slug ? `/${slug}` : undefined,
    data,
  };
}

// ── Taxonomy Parsers ─────────────────────────────────────────────

function parseAuthor(xml: string, locale: string): Document {
  const login = extractTag(xml, 'wp:author_login');
  return {
    contentType: 'author',
    locale,
    path: `/_authors/${login}`,
    data: {
      login,
      email: extractTag(xml, 'wp:author_email'),
      displayName: extractTag(xml, 'wp:author_display_name'),
      firstName: extractTag(xml, 'wp:author_first_name'),
      lastName: extractTag(xml, 'wp:author_last_name'),
    },
  };
}

function parseCategory(xml: string, locale: string): Document {
  const slug = extractTag(xml, 'wp:category_nicename');
  return {
    contentType: 'category',
    locale,
    path: `/_categories/${slug}`,
    data: {
      name: extractTag(xml, 'wp:cat_name'),
      slug,
      parent: extractTag(xml, 'wp:category_parent') || null,
    },
  };
}

function parseTagDoc(xml: string, locale: string): Document {
  const slug = extractTag(xml, 'wp:term_slug');
  return {
    contentType: 'tag',
    locale,
    path: `/_tags/${slug}`,
    data: {
      name: extractTag(xml, 'wp:term_name'),
      slug,
    },
  };
}

// ── Gutenberg Block Comment Stripper ─────────────────────────────

/**
 * Strip WordPress Gutenberg block comments from HTML content.
 *
 * Removes patterns like:
 * - `<!-- wp:paragraph -->`
 * - `<!-- wp:heading {"level":3} -->`
 * - `<!-- /wp:paragraph -->`
 */
export function stripGutenbergComments(html: string): string {
  if (!html) return '';
  return html.replace(/<!-- \/?\s*wp:\S+[\s\S]*?-->\n?/g, '').trim();
}

// ── XML Extraction Helpers ───────────────────────────────────────

/**
 * CDATA-aware block extraction.
 * Correctly skips over CDATA sections that might contain
 * text resembling closing tags.
 */
function extractBlocksSafe(xml: string, tag: string): string[] {
  const blocks: string[] = [];
  const openTag = `<${tag}`;
  const closeTag = `</${tag}>`;
  let i = 0;

  while (i < xml.length) {
    const start = xml.indexOf(openTag, i);
    if (start === -1) break;

    const openEnd = xml.indexOf('>', start + openTag.length);
    if (openEnd === -1) break;

    let j = openEnd + 1;
    let found = false;
    while (j < xml.length) {
      if (xml.startsWith('<![CDATA[', j)) {
        const cdataEnd = xml.indexOf(']]>', j + 9);
        j = cdataEnd === -1 ? xml.length : cdataEnd + 3;
        continue;
      }
      if (xml.startsWith(closeTag, j)) {
        blocks.push(xml.substring(start, j + closeTag.length));
        j += closeTag.length;
        found = true;
        break;
      }
      j++;
    }
    i = found ? j : openEnd + 1;
  }

  return blocks;
}

/** Extract blocks using simple regex (for tags without CDATA conflicts). */
function extractBlocks(xml: string, tag: string): string[] {
  const re = new RegExp(`<${escRe(tag)}[^>]*>[\\s\\S]*?</${escRe(tag)}>`, 'g');
  return [...xml.matchAll(re)].map(m => m[0]);
}

/** Extract the first block matching a tag. */
function extractFirstBlock(xml: string, tag: string): string | null {
  const re = new RegExp(`<${escRe(tag)}[^>]*>[\\s\\S]*?</${escRe(tag)}>`, 'i');
  const m = xml.match(re);
  return m ? m[0] : null;
}

/** Extract text content of the first occurrence of a tag, decoding CDATA. */
function extractTag(xml: string, tag: string): string {
  const openTag = `<${tag}`;
  const closeTag = `</${tag}>`;

  const start = xml.indexOf(openTag);
  if (start === -1) return '';

  const openEnd = xml.indexOf('>', start + openTag.length);
  if (openEnd === -1) return '';

  const closeStart = xml.indexOf(closeTag, openEnd + 1);
  if (closeStart === -1) return '';

  const content = xml.substring(openEnd + 1, closeStart);
  return decodeCDATA(content.trim());
}

/** Extract simple text tag content (no CDATA, used for <link>). */
function extractSimpleTag(xml: string, tag: string): string {
  const re = new RegExp(`<${escRe(tag)}>([^<]+)</${escRe(tag)}>`, 'i');
  const m = xml.match(re);
  return m ? m[1].trim() : '';
}

/** Remove CDATA wrappers from text. */
function decodeCDATA(text: string): string {
  return text.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1');
}

/** Extract inline <category> elements assigned to a post. */
function extractInlineTerms(xml: string): { categories: string[]; tags: string[] } {
  const categories: string[] = [];
  const tags: string[] = [];
  const re = /<category\s+domain="([^"]+)"\s+nicename="[^"]*"><!\[CDATA\[(.*?)\]\]><\/category>/g;
  let m;
  while ((m = re.exec(xml)) !== null) {
    if (m[1] === 'category') categories.push(m[2]);
    else if (m[1] === 'post_tag') tags.push(m[2]);
  }
  return { categories, tags };
}

/** Extract <wp:postmeta> key/value pairs (skips internal _prefixed keys). */
function extractPostMeta(xml: string): Record<string, string> {
  const meta: Record<string, string> = {};
  for (const block of extractBlocks(xml, 'wp:postmeta')) {
    const key = extractTag(block, 'wp:meta_key');
    const value = extractTag(block, 'wp:meta_value');
    if (key && !key.startsWith('_')) {
      meta[key] = value;
    }
  }
  return meta;
}

/** Convert WP date string to ISO 8601. */
function toISO(dateStr: string): string {
  const d = new Date(dateStr.includes('T') ? dateStr : dateStr + 'Z');
  return isNaN(d.getTime()) ? dateStr : d.toISOString();
}

/** Guess MIME type from file extension. */
function guessMimeType(url: string): string {
  const ext = url.split('.').pop()?.toLowerCase() || '';
  const map: Record<string, string> = {
    jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png',
    gif: 'image/gif', webp: 'image/webp', svg: 'image/svg+xml',
    pdf: 'application/pdf', mp3: 'audio/mpeg', mp4: 'video/mp4',
  };
  return map[ext] || 'application/octet-stream';
}

/** Escape special regex characters. */
function escRe(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
